export const TimeWindows = {
  CRON_INTERVAL_MINUTES:   10,
  DEFAULT:                 30,
  STREAK_ONGOING:          30,
  STREAK_BREAK:            14,
  CHECKLIST:                1,
  MILESTONE:         Infinity,
  THRESHOLD_TODAY:          1,
  THRESHOLD_RANGE:         30,
  ITEM_ANALYSIS_TODAY:      1,
  ITEM_ANALYSIS_RANGE:     30,
  ACTIVITY_PATTERN:        30,
  RECOMMENDATION:          30,
  ORG_BENCHMARK_THIS_WEEK:  7,
  ORG_BENCHMARK_LAST_WEEK: 14,
}
